// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IDInterface interface {
	IsIDInterface()
	GetID() string
}

type NewUser struct {
	Name string  `json:"name"`
	Dob  *string `json:"dob,omitempty"`
}

type NewVideo struct {
	Title  string `json:"title"`
	URL    string `json:"url"`
	UserID string `json:"userId"`
}

type Video struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	URL    string `json:"url"`
	Author *User  `json:"author"`
}

func (Video) IsIDInterface()     {}
func (this Video) GetID() string { return this.ID }
